# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1--V6UL7YaY8cIRnggNk_YnqvuKw8vInt
"""

# Listagem 6.1

L = []

# Essa sintaxe cria uma lista chamada L com zero elemento, ou seja, uma lista vazia.