# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1--V6UL7YaY8cIRnggNk_YnqvuKw8vInt
"""

# Listagem 6.10

L = [1, 2, 3, 4, 5]

V = L[0:5]

[1, 2, 3, 4, 5]

L[:5]

[1, 2, 3, 4, 5]

L[:-1]

[1, 2, 3, 4]

L[1:3]

[2, 3]

L[1:4]

[2, 3, 4]

L[3:]

[4, 5]

L[:3]

[1, 2, 3]

L[-1]

5

L[-2]

4

# Observe que índices negativos também funcionam. Um índice negativo começa a contar do último elemento, mas observe que começamos de -1. Assim L[0] representa o primeiro elemento; L[-1], o último; L[-2], o penúltimo, e assim por diante.