# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1--V6UL7YaY8cIRnggNk_YnqvuKw8vInt
"""

# Listagem 6.7

notas = [0, 0, 0, 0, 0]

x = 0

while x<5:
    numeros[x] = int (input ("Número %d: " % (x+1)))
  
    x += 1

while true:
    escolhido = i   (input("Que posição você quer imprimir (0 para sair): "))
    if escolhido == 0
      break
    print("Você escolheu o número: %d" % (numeros[escolhido-1]))