# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1--V6UL7YaY8cIRnggNk_YnqvuKw8vInt
"""

# Listagem 6.3

ListaComElementos[0]
ListaComElementos[1]
ListaComElementos[2]

# Utilizando o nome da lista e um índice, pode-se mudar o conteúdo de um elemento.