# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1--V6UL7YaY8cIRnggNk_YnqvuKw8vInt
"""

# Listagem 6.4

ListaComElementos[0] = 7
ListaComElementos[0]

ListaComElementos

# Nesta sintaxe está sendo feito a modificação de um valor armazenado dentro de uma variável.