# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1--V6UL7YaY8cIRnggNk_YnqvuKw8vInt
"""

# Listagem 6.2

Z = [15, 8, 9]

# A lista Z foi criada com três elementos: 15, 8 e 9. Diz-se que o tamanho da lista
Z é 3.