# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1--V6UL7YaY8cIRnggNk_YnqvuKw8vInt
"""

# Listagem 6.5

notas = [6, 7, 5, 8, 9]

soma = 0

x = 0

while x<5:
    soma += notas[x]
    x += 1

   print("Média: %5.2f" % (soma/x)) 

# Nesta sintaxe está sendo realizado o cálculo médio de notas.