# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1--V6UL7YaY8cIRnggNk_YnqvuKw8vInt
"""

# Listagem 6.9
L = [1, 2, 3, 4, 5]

V = L[:]

v[0] = 6

L 

[1, 2, 3, 4, 5]

V

[6, 2, 3, 4, 5]

# Ao escrevermos L[:], estamos nos referindo a uma nova cópia de L. Assim L e v se referem a áreas diferentes na memória, permitindo alterá-las de forma independente.