# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JyhFAbAjJt7XLEx2mSHZ1C3UsXfvGilo
"""

# Listagem 6.11

L = [12, 9, 5]

len(L)

3

v = []

len(v)

0

# A função len pode ser utilizada em repetições para controlar o limite dos índices.